[package]
name = "spacerobo_shooting_range_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
spacerobo_commons = { workspace = true }
avian3d = { workspace = true }
bevy = { workspace = true }
