[package]
name = "spacerobo_hud"
description = "The in-game HUD: heading, coordinates, HP and kill counter"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
bevy.workspace = true
spacerobo_commons.workspace = true

[lints]
workspace = true
