name: Rust

on:
  push:

jobs:
  ci-on-Unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.10.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run cargo-xtask
        run: nix develop --print-build-logs --command sh -c 'cargo xtask --debug --release'

  ci-on-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup rustup
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # On master (default branch)
        with:
          toolchain: 1.94.1
          components: clippy, rust-analyzer, rust-src

      - name: Run cargo-xtask
        run: cargo xtask --debug --release
